### ISSUE TITLE
duplicate lobby

### ISSUE THREAD

**Issue by ghost** [gurwinder-git/Type-Go#1]
Hello, I have a question, is it normal that from the third player who joins the lobby breaks and duplicates?

**Comment by ghost** [comment]
the client side (join) is buggy on the players (duplication from the 3rd client) but the host side has no problem)
https://i.imgur.com/imAFVf6.mp4

**Comment by gurwinder-git** [comment]
If we join from same pc then this bug will be occur, you can use different
browsers or use private window for testing.

gurwinder

**Comment by gurwinder-git** [comment]
Actually we are using local storage of browser that's why this bug
occuring. Use different devices or private browser windows.

gurwinder

**Comment by ghost** [comment]
Hello, yes and no.
I tested with 4 different PCs, the bug occurs. (friends)

Praaly.

**Comment by ghost** [comment]
HOST does not have this problem if +3 people CUSTOMER arrives (the layout is displayed perfectly).
But from the client view if there are +3 clients everything will crash.

Praaly.

**Comment by ghost** [comment]
https://imgur.com/jcIVZHs
If you want to see, with 4 different browsers. (but we also tested it in group with friends.

**Comment by ghost** [comment]
Can you try on your side to keep me informed it would be nice (for me the problem comes from joingame)
Praaly

**Comment by gurwinder-git** [comment]
I tested lot but it's fine. I don't know where's the problem.🙄

gurwinder

**Comment by ghost** [comment]
Can we talk on discord? Praaly#1036

**Comment by ghost** [comment]
We tried again on your link, a buddy in stream tested your site, and as you can see (him side client) he saw well 1 person in excess (which is a duplication) this bug occurred when the 3rd person client) so 4 in all).

https://imgur.com/a/gjcENWN

**Comment by ghost** [comment]
Keep me informed.
Praaly.

**Comment by ghost** [comment]
It's sad that you don't give any news about the bug if there are more than 4 customers connected...

**Comment by ghost** [comment]
Again, test on 4 different browsers, on 4 different PCs, on your official SITE.

TEST HERE : https://type-go-multiplayer.herokuapp.com/

We always have this error https://i.imgur.com/R8Kp0qB.gif

**Comment by gurwinder-git** [comment]
Yes, bug is there in Future I'll try to fix it.

gurwinder

**Comment by gurwinder-git** [comment]
Hello,
Bug is fixed I will update website after 8:00 pm
Thank you

gurwinder
